apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-controller-rbac
  namespace: demo-system
rules:
- apiGroups: ["app.cjq.io"]
  resources: ["myapps"]
  verbs: ["get","watch","list","create","update","delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list","create","update","delete"]
- apiGroups: [""]  #建议空
  resources: ["services"]
  verbs: ["get","watch","list","create","update","delete"]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-controller-rbac-rolebinding
  namespace: demo-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: demo-system
roleRef:
  kind: ClusterRole
  name: pod-controller-rbac
  apiGroup: rbac.authorization.k8s.io
