# permissions for end users to edit etcdbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdbackup-editor-role
rules:
- apiGroups:
  - etcd.cjq.io
  resources:
  - etcdbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.cjq.io
  resources:
  - etcdbackups/status
  verbs:
  - get
