id: cassandra
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: cassandra
    containers:
      - name: cassandra
        image: kubernetes/cassandra:v1
        command:
          - /run.sh
        cpu: 1000
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
        volumeMounts:
          - name: data
            mountPath: /cassandra_data
        env:
          - key: MAX_HEAP_SIZE
            value: 512M
          - key: HEAP_NEWSIZE
            value: 100M
          - key: KUBERNETES_API_PROTOCOL
            value: http
    volumes:
      - name: data
        source:
          emptyDir: {}
labels:
  name: cassandra

    
