# permissions for end users to view gatewayproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayproxy-viewer-role
rules:
- apiGroups:
  - gogateway.cjq.io
  resources:
  - gatewayproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gogateway.cjq.io
  resources:
  - gatewayproxies/status
  verbs:
  - get
