/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/20gu00/crd-controller/pkg/apis/stableexamplecom/v1"
	scheme "github.com/20gu00/crd-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CronTabsGetter has a method to return a CronTabInterface.
// A group's client should implement this interface.
type CronTabsGetter interface {
	CronTabs(namespace string) CronTabInterface
}

// CronTabInterface has methods to work with CronTab resources.
type CronTabInterface interface {
	Create(ctx context.Context, cronTab *v1.CronTab, opts metav1.CreateOptions) (*v1.CronTab, error)
	Update(ctx context.Context, cronTab *v1.CronTab, opts metav1.UpdateOptions) (*v1.CronTab, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CronTab, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CronTabList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CronTab, err error)
	CronTabExpansion
}

// cronTabs implements CronTabInterface
type cronTabs struct {
	client rest.Interface
	ns     string
}

// newCronTabs returns a CronTabs
func newCronTabs(c *StableV1Client, namespace string) *cronTabs {
	return &cronTabs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cronTab, and returns the corresponding cronTab object, and an error if there is any.
func (c *cronTabs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CronTab, err error) {
	result = &v1.CronTab{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CronTabs that match those selectors.
func (c *cronTabs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CronTabList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CronTabList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cronTabs.
func (c *cronTabs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cronTab and creates it.  Returns the server's representation of the cronTab, and an error, if there is any.
func (c *cronTabs) Create(ctx context.Context, cronTab *v1.CronTab, opts metav1.CreateOptions) (result *v1.CronTab, err error) {
	result = &v1.CronTab{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cronTab).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cronTab and updates it. Returns the server's representation of the cronTab, and an error, if there is any.
func (c *cronTabs) Update(ctx context.Context, cronTab *v1.CronTab, opts metav1.UpdateOptions) (result *v1.CronTab, err error) {
	result = &v1.CronTab{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crontabs").
		Name(cronTab.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cronTab).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cronTab and deletes it. Returns an error if one occurs.
func (c *cronTabs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crontabs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cronTabs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cronTab.
func (c *cronTabs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CronTab, err error) {
	result = &v1.CronTab{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crontabs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
