# permissions for end users to edit redissingles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redissingle-editor-role
rules:
- apiGroups:
  - app.cjq.io
  resources:
  - redissingles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cjq.io
  resources:
  - redissingles/status
  verbs:
  - get
