/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	stableexamplecomv1 "github.com/20gu00/crd-controller/pkg/apis/stableexamplecom/v1"
	versioned "github.com/20gu00/crd-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/20gu00/crd-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/20gu00/crd-controller/pkg/client/listers/stableexamplecom/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CronTabInformer provides access to a shared informer and lister for
// CronTabs.
type CronTabInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CronTabLister
}

type cronTabInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCronTabInformer constructs a new informer for CronTab type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCronTabInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCronTabInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCronTabInformer constructs a new informer for CronTab type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCronTabInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StableV1().CronTabs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StableV1().CronTabs(namespace).Watch(context.TODO(), options)
			},
		},
		&stableexamplecomv1.CronTab{},
		resyncPeriod,
		indexers,
	)
}

func (f *cronTabInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCronTabInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cronTabInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&stableexamplecomv1.CronTab{}, f.defaultInformer)
}

func (f *cronTabInformer) Lister() v1.CronTabLister {
	return v1.NewCronTabLister(f.Informer().GetIndexer())
}
