id: hazelcast
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: hazelcast
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: hazelcast
        containers:
          - name: hazelcast
            image: pires/hazelcast-k8s
            cpu: 1000
            ports:
              - name: hazelcast
                containerPort: 5701
    labels:
      name: hazelcast
