apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-registry
  labels:
    app: admission-registry
spec:
  selector:
    matchLabels:
      app: admission-registry
  template:
    metadata:
      labels:
        app: admission-registry
    spec:
#      initContainers:
#        - name: xxx
#          image: xxx
#          imagePullPolicy: IfNotPresent
#          # 初始化容器自身执行完毕就退出了不会留下任何东西,这里使用了volume
#          volumeMounts:
#            - name: webhook-certs
#              mountPath: /etc/webhook/certs
#              readOnly: true
      containers:
        - name: whitelist
          image: 010101010007/admission-registry:v0.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: WHITEIPS_REGISTRY
              value: "docker.io,gcr.io"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-registry-tls
          # 可以换掉secret
          #emptyDir{}
---
apiVersion: v1
kind: Service
metadata:
  name: admission-registry
  labels:
    app: admission-registry
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-registry