# validatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
  - name: io.ydzs.admission-registry  # 唯一即可
    rules:
      # webhook操作资源的权限
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      #apiserver相当于客户端,请求webhook webhook是server端
      service:
        namespace: default
        name: admission-registry
        path: "/validate"
      # api-server相当于客户端,发送请求是带上服务端证书文件
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVRmRTaElWNTNtTUxubFkvUzErSk8xWFYyYzVRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl6TURFeE1qSXpNVEV3TUZvWERUSTRNREV4TVRJek1URXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMzNlUm5CbEZCdTk4L2E0UFkxOFMKeTNxYmxEdTFZMlQyMHhaM2FYa3RwVjJndUxkakhKOGpUTGJtcnp4WXJvenlUSWRNM2g5NFdPallkc0t5VHhqYQpiQUxJWG44bDJPY1B6bUJTZndweUoyRWdmRDdDWVhUazVBdWFyWmJTa0plT3BmQlhkMGJya20xS2p0aC92cVd4CmxYVXduQ1dSL2diTWk0U1U3dDY1MElSZ1FLWTVkb3lVaWJOZFpreC8wbXhDbG1xSWNSV0tUTEtuVjBkcUFOWGIKMUtPMzNUSzhRdW44UmdGRlpoczBPeXVmSnRkSHhWbkVuZWUra1VERXp6eG5BT0Rxc2twY2dhU014WVBQck90UgpBRjkwaUhhT3VFc2pqOSt3VUdKZnoxeGpweWZGVURZUEVDczN2TE13b1liRll0azZIeFhjNVk3UDBKeXFjUXJMClVRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVZUNSZExtd3Q5NWhqbGVqRjc1OFAwTllwSWtNd0h3WURWUjBqQkJnd0ZvQVVlQ1JkTG13dAo5NWhqbGVqRjc1OFAwTllwSWtNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGZWpRTXdCU05ZRDRWekdXaUdUCmF6R2NtU2ZjM0doK0xCUkdxamhtS2NyUUZLRzZ5ZG5GNXFKRXU5dXJQZUtRVERGL01yMUVCRTRQdC9TcXM5WkUKZVc5Y3M2cFdybVd2MFNvKzJGd1lrTExFR0djYVAyZER0bGpmN0I1OEpZaEJLRGJPcEhONUQ5SWtsTTNnbDJvYwo5b2ZoaVRGNkVSVFJlUXlRWnh3d1lOYUN4Y3I2MEFHYVFhQzhTdGpKZWNTUlpyU3lYV3JUNFIwMVV1SVlkOHpmCmM2ajJkNS8vZDJ1Y1BobWZVSjhQTExHWThOQmFpTUdlb21NYXQrVDc0UDBhUDRxbmxQcEwzZnhQdDRjRlRWQ1UKN0VVdzhvcUQzSU82eVhCV1ZFQk11ek1DaHp0Qy9aV3BXd2Fab0wwdlgrWUlPNjZHSFhlMlRRa0MvVW14My85YQp4LzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-registry-mutate
webhooks:
  - name: io.ydzs.admission-registry-mutate
    clientConfig:
      service:
        namespace: default
        name: admission-registry
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVRmRTaElWNTNtTUxubFkvUzErSk8xWFYyYzVRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl6TURFeE1qSXpNVEV3TUZvWERUSTRNREV4TVRJek1URXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMzNlUm5CbEZCdTk4L2E0UFkxOFMKeTNxYmxEdTFZMlQyMHhaM2FYa3RwVjJndUxkakhKOGpUTGJtcnp4WXJvenlUSWRNM2g5NFdPallkc0t5VHhqYQpiQUxJWG44bDJPY1B6bUJTZndweUoyRWdmRDdDWVhUazVBdWFyWmJTa0plT3BmQlhkMGJya20xS2p0aC92cVd4CmxYVXduQ1dSL2diTWk0U1U3dDY1MElSZ1FLWTVkb3lVaWJOZFpreC8wbXhDbG1xSWNSV0tUTEtuVjBkcUFOWGIKMUtPMzNUSzhRdW44UmdGRlpoczBPeXVmSnRkSHhWbkVuZWUra1VERXp6eG5BT0Rxc2twY2dhU014WVBQck90UgpBRjkwaUhhT3VFc2pqOSt3VUdKZnoxeGpweWZGVURZUEVDczN2TE13b1liRll0azZIeFhjNVk3UDBKeXFjUXJMClVRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVZUNSZExtd3Q5NWhqbGVqRjc1OFAwTllwSWtNd0h3WURWUjBqQkJnd0ZvQVVlQ1JkTG13dAo5NWhqbGVqRjc1OFAwTllwSWtNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGZWpRTXdCU05ZRDRWekdXaUdUCmF6R2NtU2ZjM0doK0xCUkdxamhtS2NyUUZLRzZ5ZG5GNXFKRXU5dXJQZUtRVERGL01yMUVCRTRQdC9TcXM5WkUKZVc5Y3M2cFdybVd2MFNvKzJGd1lrTExFR0djYVAyZER0bGpmN0I1OEpZaEJLRGJPcEhONUQ5SWtsTTNnbDJvYwo5b2ZoaVRGNkVSVFJlUXlRWnh3d1lOYUN4Y3I2MEFHYVFhQzhTdGpKZWNTUlpyU3lYV3JUNFIwMVV1SVlkOHpmCmM2ajJkNS8vZDJ1Y1BobWZVSjhQTExHWThOQmFpTUdlb21NYXQrVDc0UDBhUDRxbmxQcEwzZnhQdDRjRlRWQ1UKN0VVdzhvcUQzSU82eVhCV1ZFQk11ek1DaHp0Qy9aV3BXd2Fab0wwdlgrWUlPNjZHSFhlMlRRa0MvVW14My85YQp4LzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None