apiVersion: "v1beta1"
id: "monitoring-heapster-controller"
kind: "ReplicationController"
desiredState: 
  replicas: 1
  replicaSelector:    
    name: "heapster"
  podTemplate:
    desiredState:
      manifest:
        version: "v1beta1"
        id: "monitoring-heapster-controller"
        containers:
          - name: "heapster"
            image: "kubernetes/heapster:v0.6"
            env: 
              - name: "INFLUXDB_HOST"
                value: "monitoring-influxdb"

    labels: 
      name: "heapster"
      uses: "monitoring-influxdb"
labels: 
  name: "heapster"
