apiVersion: "v1beta1"
kind: "ReplicationController"
id: "monitoring-influx-grafana-controller"
desiredState: 
  replicas: 1
  replicaSelector:
    name: "influxGrafana"
  podTemplate:
    labels:
      name: "influxGrafana"
    desiredState:
      manifest:
        version: "v1beta1"
        id: "monitoring-influx-grafana-controller"
        containers: 
          - name: "influxdb"
            image: "kubernetes/heapster_influxdb:v0.3"
            ports: 
              - containerPort: 8083
                hostPort: 8083
              - containerPort: 8086
                hostPort: 8086
          - name: "grafana"
            image: "kubernetes/heapster_grafana:v0.3"
            ports: 
              - containerPort: 80
                hostPort: 80
            env: 
              - name: "HTTP_USER"
                value: "admin"
              - name: "HTTP_PASS"
                value: "**None**"
labels:
  name: "influxGrafana"
