# permissions for end users to edit masterslaves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: masterslave-editor-role
rules:
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - masterslaves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - masterslaves/status
  verbs:
  - get
