# permissions for end users to view masterslaves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: masterslave-viewer-role
rules:
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - masterslaves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - masterslaves/status
  verbs:
  - get
