apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: incluster-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]  #resetful的resources
    verbs: ["get","list","watch"]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: incluster-rbac-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: incluster-role
  apiGroup: rbac.authorization.k8s.io
