id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: redis-master
    containers:
      - name: master
        image: kubernetes/redis:v1
        cpu: 1000
        ports:
          - name: api
            containerPort: 6379
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
        env:
          - key: MASTER
            value: "true"
      - name: sentinel
        image: kubernetes/redis:v1
        ports:
          - name: api
            containerPort: 26379
        env:
          - key: SENTINEL
            value: "true"
    volumes:
      - name: data
        source:
          emptyDir: {}
labels:
  name: redis
  role: master
  redis-sentinel: "true"

    
