id: redis-slave
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: redis-slave
    containers:
      - name: slave
        image: kubernetes/redis:v1
        cpu: 1000
        ports:
          - name: api
            containerPort: 6379
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
    volumes:
      - name: data
        source:
          emptyDir: {}
labels:
  name: redis


    
