id: redis
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: redis
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: redis
        containers:
          - name: redis
            image: kubernetes/redis:v1
            cpu: 1000
            ports:
              - name: api
                containerPort: 6379
            volumeMounts:
              - name: data
                mountPath: /redis-master-data
        volumes:
          - name: data
            source:
              emptyDir: {}
    labels:
      name: redis

