# permissions for end users to view mysqlsingles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlsingle-viewer-role
rules:
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - mysqlsingles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cjqapp.cjq.io
  resources:
  - mysqlsingles/status
  verbs:
  - get
