apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-6379-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-provisioner"  # 这里指定storageClass名称
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-provisioner
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
spec:
  storageClassName: "nfs-provisioner"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/redis  # 指定nfs的挂载点
    server: 192.168.23.232  # 指定nfs服务地址，这是我node1的主机ip
