/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/20gu00/crd-controller/pkg/apis/stableexamplecom/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CronTabLister helps list CronTabs.
// All objects returned here must be treated as read-only.
type CronTabLister interface {
	// List lists all CronTabs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.CronTab, err error)
	// CronTabs returns an object that can list and get CronTabs.
	CronTabs(namespace string) CronTabNamespaceLister
	CronTabListerExpansion
}

// cronTabLister implements the CronTabLister interface.
type cronTabLister struct {
	indexer cache.Indexer
}

// NewCronTabLister returns a new CronTabLister.
func NewCronTabLister(indexer cache.Indexer) CronTabLister {
	return &cronTabLister{indexer: indexer}
}

// List lists all CronTabs in the indexer.
func (s *cronTabLister) List(selector labels.Selector) (ret []*v1.CronTab, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.CronTab))
	})
	return ret, err
}

// CronTabs returns an object that can list and get CronTabs.
func (s *cronTabLister) CronTabs(namespace string) CronTabNamespaceLister {
	return cronTabNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CronTabNamespaceLister helps list and get CronTabs.
// All objects returned here must be treated as read-only.
type CronTabNamespaceLister interface {
	// List lists all CronTabs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.CronTab, err error)
	// Get retrieves the CronTab from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.CronTab, error)
	CronTabNamespaceListerExpansion
}

// cronTabNamespaceLister implements the CronTabNamespaceLister
// interface.
type cronTabNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CronTabs in the indexer for a given namespace.
func (s cronTabNamespaceLister) List(selector labels.Selector) (ret []*v1.CronTab, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.CronTab))
	})
	return ret, err
}

// Get retrieves the CronTab from the indexer for a given namespace and name.
func (s cronTabNamespaceLister) Get(name string) (*v1.CronTab, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("crontab"), name)
	}
	return obj.(*v1.CronTab), nil
}
