# permissions for end users to view redissts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redissts-viewer-role
rules:
- apiGroups:
  - app.cjq.io
  resources:
  - redissts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.cjq.io
  resources:
  - redissts/status
  verbs:
  - get
