language: go

go:
  - 1.3
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/golang.org/x"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/golang.org/x/oauth2"
  - go get -v -t -d -tags='appengine appenginevm' golang.org/x/oauth2/...

script:
  - go test -v -tags='appengine appenginevm' golang.org/x/oauth2/...
